### ISSUE TITLE
Dependency fails to load using uglifyjs

### ISSUE THREAD

**Issue by victorhqc** [Avocarrot/authentication-client#14]
Maybe the project needs to be built at certain point? Right now it is imported as many independent and unminified files.

Our uglifyjs configuration complains about `es6`
<img width="962" alt="screen shot 2017-05-19 at 15 33 39" src="https://cloud.githubusercontent.com/assets/726113/26249936/a8dad1be-3ca8-11e7-9c1a-5a849b1b0acf.png">

**Comment by devlato** [comment]
@emiliosnic We faced the problem. Our build tools uses UglifyJS for minification & obfuscation of the code, and UglifyJS expects all the exported items of the third party libraries from `node_modules` to be in ES5, so uglification fails because you have some ES6 syntax there (i.e you have string interpolation. in `utils/index.js`). 
Could you please add a step to your CircleCI to build a ES5 version and publish it somewhere? (I gues you could even publish it to this repo with some specific tag).
